# Generated by Django 4.1 on 2022-09-03 15:43

import candidates.vpresidency.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CongresistaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=candidates.vpresidency.models.CongresistaModel.Pcant_url)),
            ],
            options={
                'verbose_name': 'Congresista',
                'verbose_name_plural': 'Congresista',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ParAndinoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=candidates.vpresidency.models.ParAndinoModel.Scant_url)),
            ],
            options={
                'verbose_name': 'Parlamento',
                'verbose_name_plural': 'Parlamentos',
                'ordering': ['id'],
            },
        ),
    ]
