# Generated by Django 4.1 on 2022-09-02 21:33

import candidates.presidency.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politc_p', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Politic',
                'verbose_name_plural': 'Politics',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studes', models.CharField(max_length=500, verbose_name='Estudios')),
            ],
            options={
                'verbose_name': 'Stude',
                'verbose_name_plural': 'Studes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PresidencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('birthday', models.DateField(default=datetime.datetime.now)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=candidates.presidency.models.PresidencyModel.pre_url, verbose_name='Foto')),
                ('politic_part', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='presidency.politicmodel')),
                ('studes', models.ManyToManyField(blank=True, null=True, to='presidency.studies')),
            ],
            options={
                'verbose_name': 'Presiden',
                'verbose_name_plural': 'Presidency',
                'ordering': ['id'],
            },
        ),
    ]
