# Generated by Django 4.1 on 2022-09-03 15:43

import candidates.presidency.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vpresidency', '0001_initial'),
        ('presidency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presidencymodel',
            name='congresista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vpresidency.congresistamodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='presidencymodel',
            name='parlamento_andino',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vpresidency.parandinomodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presidencymodel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=candidates.presidency.models.PresidencyModel.pre_url),
        ),
    ]
